version: "3.3"

services:
  backend:
    build:
      context: ../be_open_api
      dockerfile: Dockerfile
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/node_modules:/usr/app/node_modules
      - ./frontend:/usr/app
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8061:8061"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

