export const GETTING_USER_DETAILS = "GETTING_USER_DETAILS";
export const GETTING_USER_DETAILS_SUCCESSFUL = "GETTING_USER_DETAILS_SUCCESSFUL";
export const GETTING_USER_DETAILS_ERROR = "GETTING_USER_DETAILS_ERROR";
export const CHANGE_LOGOUT = "CHANGE_LOGOUT";
