export const ACTIVATE_LOADING = "ACTIVATE_LOADING";
export const DEACTIVATE_LOADING = "DEACTIVATE_LOADING";

export const SHOW_CONFIRM_DISCONNECT_DIALOG = "SHOW_CONFIRM_DISCONNECT_DIALOG";
export const CLOSE_CONFIRM_DISCONNECT_DIALOG = "CLOSE_CONFIRM_DISCONNECT_DIALOG";

export const SHOW_CONFIRM_RECONNECT_DIALOG = "SHOW_CONFIRM_RECONNECT_DIALOG";
export const CLOSE_CONFIRM_RECONNECT_DIALOG = "CLOSE_CONFIRM_RECONNECT_DIALOG";

export const SETTING_GRID_API = "SETTING_GRID_API";

export const GETTING_EXTERNAL_VENDOR = "GETTING_EXTERNAL_VENDOR";
export const GETTING_EXTERNAL_VENDOR_ERROR = "GETTING_EXTERNAL_VENDOR_ERROR";
export const GETTING_EXTERNAL_VENDOR_SUCCESSFUL = "GETTING_EXTERNAL_VENDOR_SUCCESSFUL";

export const GETTING_PAYMENT_TERM = "GETTING_PAYMENT_TERM";
export const GETTING_PAYMENT_TERM_ERROR = "GETTING_PAYMENT_TERM_ERROR";
export const GETTING_PAYMENT_TERM_SUCCESSFUL = "GETTING_PAYMENT_TERM_SUCCESSFUL";

export const GETTING_BANK_ACCOUNT = "GETTING_BANK_ACCOUNT";
export const GETTING_BANK_ACCOUNT_ERROR = "GETTING_BANK_ACCOUNT_ERROR";
export const GETTING_BANK_ACCOUNT_SUCCESSFUL = "GETTING_BANK_ACCOUNT_SUCCESSFUL";

export const CREATING_EXTERNAL_VENDOR = "CREATING_EXTERNAL_VENDOR";
export const CREATING_EXTERNAL_VENDOR_ERROR = "CREATING_EXTERNAL_VENDOR_ERROR";
export const CREATING_EXTERNAL_VENDOR_SUCCESSFUL = "CREATING_EXTERNAL_VENDOR_SUCCESSFUL";

export const DISCONNECT_SUPPLIER = "DISCONNECT_SUPPLIER";
export const DISCONNECT_SUPPLIER_SUCCESSFUL = "DISCONNECT_SUPPLIER_SUCCESSFUL";
export const DISCONNECT_SUPPLIER_ERROR = "DISCONNECT_SUPPLIER_ERROR";

export const SETTING_UUID_SUPPLIER_DISCONNECT = "SETTING_UUID_SUPPLIER_DISCONNECT";

export const FILTER_BUYER_AND_SELLER = "FILTER_BUYER_AND_SELLER";

export const GETTING_VENDOR_DETAIL = "GETTING_VENDOR_DETAIL";
export const GETTING_VENDOR_DETAIL_SUCCESSFUL = "GETTING_VENDOR_DETAIL_SUCCESSFUL";
export const GETTING_VENDOR_DETAIL_ERROR = "GETTING_VENDOR_DETAIL_ERROR";

export const UPDATE_STATE = "UPDATE_STATE";

export const RECONNECT_SUPPLIER = "RECONNECT_SUPPLIER";
export const RECONNECT_SUPPLIER_SUCCESSFUL = "RECONNECT_SUPPLIER_SUCCESSFUL";
export const RECONNECT_SUPPLIER_ERROR = "RECONNECT_SUPPLIER_ERROR";

export const UPDATE_SUPPLIER_DETAIL = "UPDATE_SUPPLIER_DETAIL";
export const UPDATE_SUPPLIER_DETAIL_SUCCESSFUL = "UPDATE_SUPPLIER_DETAIL_SUCCESSFUL";
export const UPDATE_SUPPLIER_DETAIL_ERROR = "UPDATE_SUPPLIER_DETAIL_ERROR";

export const UPLOAD_DATA_VENDOR = "UPLOAD_DATA_VENDOR";
