export const GETTING_PERMISSION = "GETTING_PERMISSION";
export const GETTING_PERMISSION_SUCCESSFUL = "GETTING_PERMISSION_SUCCESSFUL";
export const GETTING_PERMISSION_ERROR = "GETTING_PERMISSION_ERROR";
export const SET_PERMISSION_CURRENT_CATE = "SET_PERMISSION_CURRENT_CATE";
export const SET_PERMISSION_FEATURE_BASED = "SET_PERMISSION_FEATURE_BASED";
export const SET_IS_BUYER = "SET_IS_BUYER";
