export const CREATE_PROJECT_TRADE = "CREATING_PROJECT_TRADE";
export const CREATE_PROJECT_TRADE_SUCCESSFUL = "CREATE_PROJECT_TRADE_SUCCESSFUL";
export const CREATE_PROJECT_TRADE_ERROR = "CREATE_PROJECT_TRADE_ERROR";

export const GETTING_PROJECT_TRADE = "GETTING_PROJECT_TRADE";
export const GETTING_PROJECT_TRADE_SUCCESSFUL = "GETTING_PROJECT_TRADE_SUCCESSFUL";
export const GETTING_PROJECT_TRADE_ERROR = "GETTING_PROJECT_TRADE_ERROR";
