import PREFIX from "./prefixUrlConfig";

const BASE_URL = process.env.BASE_URL || "http://localhost:8762/";

const ENTITIES_URL = `${BASE_URL}${PREFIX.ENTITIES}`;

const ENTITIES_TRANSACTION_PREFIX_URL = `${ENTITIES_URL}/${PREFIX.TRANSACTION}`;

const PURCHASE_URL = `${BASE_URL}${PREFIX.PURCHASE}`;

const CONTRACT_LIST_URL = `${BASE_URL}${PREFIX.CONTRACT}`;

const CONTRACT_REQUEST_FORM_URL = `${BASE_URL}${PREFIX.CONTRACT}`;
const CONVERSATION_URL = `${BASE_URL}${PREFIX.CONVERSATION}`;

const MEDIA_URL = `${BASE_URL}${PREFIX.MEDIA}`;

export {
    BASE_URL,
    ENTITIES_TRANSACTION_PREFIX_URL,
    PURCHASE_URL,
    CONTRACT_LIST_URL,
    CONTRACT_REQUEST_FORM_URL,
    ENTITIES_URL,
    MEDIA_URL,
    CONVERSATION_URL
};
